# Generated by Django 2.2.4 on 2019-08-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_basket_basketline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketline',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='main.Basket'),
        ),
        migrations.AlterField(
            model_name='basketline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Product'),
        ),
    ]
