# Generated by Django 2.2.4 on 2019-09-05 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190826_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'New'), (20, 'Paid'), (30, 'Done'), (40, 'Cancelled')], default=10)),
                ('billing_name', models.CharField(max_length=60)),
                ('billing_address1', models.CharField(max_length=200, verbose_name='enter ur address')),
                ('billing_address2', models.CharField(max_length=200, verbose_name='enter additional address')),
                ('billing_country_code', models.CharField(blank=True, default='+', max_length=3)),
                ('billing_phone_number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('billing_zip_code', models.PositiveIntegerField()),
                ('billing_country', models.CharField(max_length=8)),
                ('shipping_address1', models.CharField(max_length=200, verbose_name='enter ur address')),
                ('shipping_address2', models.CharField(max_length=200, verbose_name='enter additional address')),
                ('shipping_country_code', models.CharField(blank=True, default='+', max_length=3)),
                ('shipping_phone_number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('shipping_zip_code', models.PositiveIntegerField()),
                ('shipping_country', models.CharField(max_length=8)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'New'), (20, 'Processing'), (30, 'Sent'), (40, 'Cancelled')], default=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='main.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Product')),
            ],
        ),
    ]
