# Generated by Django 2.2.4 on 2019-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
