# Generated by Django 2.2.4 on 2019-09-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
